apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
      component: web
spec:
  containers:
    - name: client
      image: ricardosouzamorais/multi-fib-client:0.0.2
      ports:
        - containerPort: 3000